# Настройка pre-commit для запуска проверок перед коммитом
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: ['types-redis==4.6.0.20241004']
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.1.0']
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.1
    hooks:
      - id: eslint
        files: '\\.(js|ts)$'
        additional_dependencies:
          - eslint@9.9.1
          - eslint-config-prettier@9.1.0
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.10.0
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@16.10.0
          - stylelint-config-standard@36.0.0
        files: "\\.(css|scss|sass)$"
  - repo: local
    hooks:
      - id: fix-mojibake
        name: fix-mojibake
        entry: python scripts/improved_fix_mojibake.py --check
        language: system
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
