extends:
  - stylelint-config-standard
rules:
  declaration-block-no-duplicate-properties: null
  keyframes-name-pattern: null
  no-descending-specificity: null
  no-duplicate-selectors: null
  selector-id-pattern: null
  selector-type-no-unknown:
    - true
    - ignoreTypes:
        - bootstrap
  property-no-unknown:
    - true
    - ignoreProperties:
        - tap-highlight-color
        - overflow-scrolling
  alpha-value-notation: null
  rule-empty-line-before: null
  media-feature-range-notation: null
  declaration-empty-line-before: null
  color-function-notation: null
