# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "request.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\rrequest.proto\x12\x03crm"
    b'"\x1f\n\x11GetRequestReques'
    b't\x12\n\n\x02id\x18\x01 \x01(\x05"8\n\x07Req'
    b"uest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\t"
    b"object_id\x18\x02 \x01(\x05\x12\x0e\n\x06s"
    b"tatus\x18\x03 \x01(\t2D\n\x0eReque"
    b"stService\x122\n\nGetRequ"
    b"est\x12\x16.crm.GetRequest"
    b"Request\x1a\x0c.crm.Reques"
    b"tb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "request_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETREQUESTREQUEST"]._serialized_start = 22
    _globals["_GETREQUESTREQUEST"]._serialized_end = 53
    _globals["_REQUEST"]._serialized_start = 55
    _globals["_REQUEST"]._serialized_end = 111
    _globals["_REQUESTSERVICE"]._serialized_start = 113
    _globals["_REQUESTSERVICE"]._serialized_end = 181
# @@protoc_insertion_point(module_scope)
